###########
# site.url, site.title

title: '#hullCSS'
description: "The University of Hull's Official Student-led Computing Society"
facebook: publisher:'hullCSS'
logo: '{{site.baseurl}}/static/hullCSS-long.png'
google_site_verification: 'xt86OOaI8aD1yls0WjGI9cn9fhPygUn-ygjIYcRSwZU'
########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
